title: "Nuno Oliveira Fernandes"
description: "MLOps Researcher & Master's Student"
url: "https://nunoferna.github.io"
baseurl: ""

# Personal Info
author:
  name: "Nuno Oliveira Fernandes"
  email: "nuno.o.fernandes@outlook.pt"
  linkedin: "nunoferna"
  github: "nunoferna"
  location: "Madeira/Porto"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap

kramdown:
  input: GFM
  syntax_highlighter: rouge
